/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package torrentk.app

object App {
    const val appName = "DBS CLI App"
    const val version = "0.0.1"
}

fun main(args: Array<String>) {
    println("${App.appName}:: ${App.version}")
    if (args.size > 1) throw TooManyArgumentsException("Too many arguments!")
    val torrentLink = args[0]
    println(torrentLink)
}

class TooManyArgumentsException(message: String) : java.lang.Exception(message)
